# Generated by Django 4.2.6 on 2023-11-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('FC', 'Fashion'), ('FOC', 'Food Products Coupons'), ('SC', 'Shoes Coupons'), ('CC', 'Clothing Coupons'), ('SPC', 'Shopping Coupons'), ('EC', 'Electronics Coupons'), ('TCC', 'Travel Coupons Coupons'), ('ZSC', 'Zomato/swiggy Coupons')], max_length=3)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
